### ISSUE TITLE
OSError: dlopen(wemd/lib/libwemd.so, 6): image not found

### ISSUE THREAD

**Issue by Prathi1109** [lmb-freiburg/Multimodal-Future-Prediction#1]
I am running this in my Mac. I did generate the libwemd.dylib in the path 'Multimodal-Future-Prediction-master/wemd/lib'. Please let me know what is that going wrong.

**Comment by os1a** [comment]
Can you please provide more details when you get this error?
Is it during compiling or after that when running the test script?

**Comment by Prathi1109** [comment]
Thank you for your response. I didn't face the error when I changed the path in wemd.py from
lib = ctypes.cdll.LoadLibrary('wemd/lib/libwemd.so')
to
lib = ctypes.cdll.LoadLibrary('wemd/lib/libwemd.dylib')
I have noticed that .dylib is the format which will be generated in mac os instead of .so
Apparently I got another error 

UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
	 [[node encoder/conv1/Conv2D (defined at /Users/prathibha/Downloads/Multimodal-Future-Prediction-master/utils_tf.py:143)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](encoder/Pad, encoder/conv1/kernel/read)]]

**Comment by Prathi1109** [comment]
I got the error when I run the test script. I have found out that i got the above mentioned error since I am running it on CPU. Could you please confirm if the code can be run on a mac without GPU?

**Comment by os1a** [comment]
I am not really sure if it supports only CPU on mac, I have not tested it there. The data format of the tensorflow operation used our code are optimized to work for GPU and thus get the most out of them. This seems to not work under CPU.

**Comment by Prathi1109** [comment]
Ok. Thanks for letting me know :)
