### ISSUE TITLE
What is the `tb` package?

### ISSUE THREAD

**Issue by mprzewie** [lmb-freiburg/Multimodal-Future-Prediction#2]
Hello!

In the code for generating the CPI dataset, you use a `tb` utility for saving the data:

https://github.com/lmb-freiburg/Multimodal-Future-Prediction/blob/master/CPI/CPI-train.py#L5

What is this python package and how can one obtain it?

Best regards!

**Comment by os1a** [comment]
Hi,
Thanks for pointing out this issue. I have updated the CPI-train.py to remove its dependency on tb which is an internal library. Now it will write images with misc and .float3 files with a custom function called WriteFloat which is added to the file.

**Comment by os1a** [comment]
In case you do not have more questions, I would close this issue

**Comment by mprzewie** [comment]
Thanks for your reply, @os1a - it's very helpful! :)
I've got some technical issues - nothing I can't solve on my own, but they may help someone else:
- the CPI-test.py script still uses the `tb` package
- the `scipy.misc.imsave` method has been deprecated since the release `1.0` of scipy and completely removed in `1.3` release a year ago. The replacement recommended by the authors is `imageio.imwrite`. 
Cheers! :)

**Comment by os1a** [comment]
Thanks for your comments. I will update the files as needed.
