### ISSUE TITLE
EMD on CPI dataset

### ISSUE THREAD

**Issue by mprzewie** [lmb-freiburg/Multimodal-Future-Prediction#3]
Hi!

Could you specify the way (or even better, the code you've used) to evaluate the EMD metric on the CPI Dataset? The only EMD-related stuff in your code seems to be related with the SEMD metric calculated for the SDD results. 

Thanks in advance! :)

**Comment by os1a** [comment]
Hi @mprzewie 

Please have a look at the new uploaded file https://github.com/lmb-freiburg/Multimodal-Future-Prediction/blob/master/emd_cpi.py

It is a simple script which loads the ground-truth samples from CPI and the prediction files containing the parameters of mixture distribution and compute the EMD distance.

Note that we used 1000 samples from the ground-truth distribution (i.e, you need to generate the CPI test data by running the python CPI-test.py output_folder num_test_scenes 3 1000).
For the prediction, we expect three files .float3 containing the parameters of the predicted mixture model (means, sigmas, and weights) with shapes ([4,2], [4,2], [4]) assuming the predicted mixture model has four components.

Best,

**Comment by mprzewie** [comment]
Thank you so much!
